//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFac
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_Book()
        {
            this.S_Record = new HashSet<S_Record>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public int type_id { get; set; }
        public int shelf_id { get; set; }
    
        public virtual S_BookType S_BookType { get; set; }
        public virtual S_BookShelf S_BookShelf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_Record> S_Record { get; set; }
    }
}
